### ISSUE TITLE
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "xwiki"

### ISSUE THREAD

**Issue by colameo** [lavadiablo/docker-xwiki#2]
There seems to be a user/password problem in your setup.

xwiki_1   |     at com.xpn.xwiki.XWiki.getClass(XWiki.java:5477) ~[xwiki-platform-legacy-oldcore-6.4.3.jar:na]
xwiki_1   |     at com.xpn.xwiki.doc.DefaultDocumentAccessBridge.isPropertyCustomMapped(DefaultDocumentAccessBridge.java:486) ~[xwiki-platform-legacy-oldcore-6.4.3.jar:na]
xwiki_1   |     at org.xwiki.query.xwql.internal.QueryContext$PropertyInfo.isCustomMapped(QueryContext.java:153) ~[xwiki-platform-query-xwql-6.4.3.jar:na]
xwiki_1   |     at org.xwiki.query.xwql.internal.QueryContext$ObjectInfo.isCustomMapped(QueryContext.java:122) ~[xwiki-platform-query-xwql-6.4.3.jar:na]
xwiki_1   |     at org.xwiki.query.xwql.internal.hql.ObjectPrinter.print(ObjectPrinter.java:37) ~[xwiki-platform-query-xwql-6.4.3.jar:na]
xwiki_1   |     at org.xwiki.query.xwql.internal.hql.Printer.print(Printer.java:70) ~[xwiki-platform-query-xwql-6.4.3.jar:na]
xwiki_1   |     at org.xwiki.query.xwql.internal.hql.XWQLtoHQLTranslator.translate(XWQLtoHQLTranslator.java:61) ~[xwiki-platform-query-xwql-6.4.3.jar:na]
xwiki_1   |     at org.xwiki.query.xwql.internal.XWQLQueryExecutor.execute(XWQLQueryExecutor.java:79) ~[xwiki-platform-query-xwql-6.4.3.jar:na]
xwiki_1   |     ... 59 common frames omitted
xwiki_1   | Caused by: org.hibernate.exception.GenericJDBCException: Cannot open connection
xwiki_1   |     at org.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:140) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:128) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:52) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:449) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:167) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:160) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:81) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1473) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     at com.xpn.xwiki.store.XWikiHibernateBaseStore.beginTransaction(XWikiHibernateBaseStore.java:903) ~[xwiki-platform-legacy-oldcore-6.4.3.jar:na]
xwiki_1   |     at com.xpn.xwiki.store.XWikiHibernateBaseStore.beginTransaction(XWikiHibernateBaseStore.java:843) ~[xwiki-platform-legacy-oldcore-6.4.3.jar:na]
xwiki_1   |     at com.xpn.xwiki.store.XWikiHibernateStore.loadXWikiDoc(XWikiHibernateStore.java:826) ~[xwiki-platform-legacy-oldcore-6.4.3.jar:na]
xwiki_1   |     ... 71 common frames omitted
xwiki_1   | Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "xwiki"
xwiki_1   |     at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:408) ~[postgresql-9.3-1102.jdbc4.jar:na]
xwiki_1   |     at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:181) ~[postgresql-9.3-1102.jdbc4.jar:na]
xwiki_1   |     at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64) ~[postgresql-9.3-1102.jdbc4.jar:na]
xwiki_1   |     at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:144) ~[postgresql-9.3-1102.jdbc4.jar:na]
xwiki_1   |     at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29) ~[postgresql-9.3-1102.jdbc4.jar:na]
xwiki_1   |     at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21) ~[postgresql-9.3-1102.jdbc4.jar:na]
xwiki_1   |     at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31) ~[postgresql-9.3-1102.jdbc4.jar:na]
xwiki_1   |     at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.3-1102.jdbc4.jar:na]
xwiki_1   |     at org.postgresql.Driver.makeConnection(Driver.java:410) ~[postgresql-9.3-1102.jdbc4.jar:na]
xwiki_1   |     at org.postgresql.Driver.connect(Driver.java:280) ~[postgresql-9.3-1102.jdbc4.jar:na]
xwiki_1   |     at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_75]
xwiki_1   |     at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_75]
xwiki_1   |     at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:133) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:446) ~[hibernate-core-3.6.9.Final.jar:3.6.9.Final]
xwiki_1   |     ... 78 common frames omitted
xwiki_1   | 2015-05-25 16:21:55,469 [http://localhost:8082/xwiki/bin/view/Main/] WARN  o.a.s.a.RequestProcessor       - Unhandled Exception thrown: class com.xpn.xwiki.XWikiException

**Comment by lavadiablo** [comment]
@colameo When you start the container of postgresql, you need set both user name and password to xwiki via parameters. Could you try docker-compose.yml in the repository?
